name: Lighthouse CI
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v7
        with:
          urls: |
            https://comissio-nocturna-git-$GITHUB_BASE_REF.comision-nocturna-barcelona.vercel.app/
            https://comissio-nocturna-git-$GITHUB_BASE_REF.comision-nocturna-barcelona.vercel.app/blog
            https://comissio-nocturna-git-$GITHUB_BASE_REF.comision-nocturna-barcelona.vercel.app/manifesto
          budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
        env:
          GITHUB_BASE_REF: ${{ github.base_ref }}
        if: (github.base_ref != 0) || (github.base_ref != NaN
