name: Lighthouse CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v7
        with:
          urls: |
            https://comissio-nocturna-git-$BRANCH.comision-nocturna-barcelona.vercel.app/
            https://comissio-nocturna-git-$BRANCH.comision-nocturna-barcelona.vercel.app/blog
            https://comissio-nocturna-git-$BRANCH.comision-nocturna-barcelona.vercel.app/manifesto
          budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
        env:
          BRANCH: ${{ github.head_ref }}
